// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.example.administrator.rolemanage.utils.imageloader;

import javax.inject.Provider;

import dagger.internal.Factory;

public final class ImageLoader_Factory implements Factory<ImageLoader> {
  private final Provider<BaseImageLoaderStrategy> strategyProvider;

  public ImageLoader_Factory(Provider<BaseImageLoaderStrategy> strategyProvider) {
    assert strategyProvider != null;
    this.strategyProvider = strategyProvider;
  }

  @Override
  public ImageLoader get() {
    return new ImageLoader(strategyProvider.get());
  }

  public static Factory<ImageLoader> create(Provider<BaseImageLoaderStrategy> strategyProvider) {
    return new ImageLoader_Factory(strategyProvider);
  }
}
